### ISSUE TITLE
Descrição & acompanhamento do projeto

### ISSUE THREAD

**Issue by victorl2** [RonaldCamp/ImpCompiler#1]
Seria legal colocar uma breve descrição no **readme** e criar alguns **issues** para as atividades que se pretende executar. Estou curioso para acompanhar o andamento do projeto; _além de deixar o projeto mais bonito também_ :+1:

**Comment by RonaldCamp** [comment]
Valeu.. Comecei introduzindo uma breve descrição, vou tentar ir melhorando.
